spring.datasource.url=jdbc:mysql://localhost:3306/nefra_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Chromo@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Set to 'update' so it doesn't wipe your DB every time you start
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8081
spring.jpa.open-in-view=false